### ISSUE TITLE
Add support for the `-from-module` flag when init

### ISSUE THREAD

**Issue by samerbahri98** [ansible-collections/cloud.terraform#108]
##### SUMMARY

Terraform has a feature where it can initialize a working directory from a terraform module like this:
```bash
terraform init -form-module <module>
```
The ansible cloud.terraform.terraform module does not support this unfortunately. And it would be nice if this feature exists.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cloud.terraform.terraform

##### ADDITIONAL INFORMATION

I can work on it and open a pull request if everyone is busy (please indicate in the comment if you are interested in having this feature, and if you want me to work on it).

##### EXAMPLE

```yaml
- name: Deploy Nginx Ingress Controller
  cloud.terraform.terraform:
    project_path: '{{ project_dir }}'
    state: present
    from_module: terraform-iaac/nginx-controller/helm  # this should download https://registry.terraform.io/modules/terraform-iaac/nginx-controller/helm/latest
```
