### ISSUE TITLE
Terraform state inventory plugin should support multiple cloud providers

### ISSUE THREAD

**Issue by vvarga007** [ansible-collections/cloud.terraform#148]
##### SUMMARY

Terraform state inventory should support multiple cloud providers and provide the capability to support in-house developed providers/resources. Currently, only three major cloud provider resources are supported. (AWS, Azure, GCP).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

terraform_state inventory plugin

##### ADDITIONAL INFORMATION

I opened a pull request with my proposed solution: ansible-collections/cloud.terraform#146

Example usage for Digital Ocean resources:
```yaml
plugin: cloud.terraform.terraform_state
backend_type: s3
backend_config:
 region: us-east-1
 key: terraform/state
 bucket: my-sample-bucket
hostnames:
 - id
groups:
 nyc: region == 'nyc3'
provider_mapping:
 - name: do
   provider_name: registry.terraform.io/digitalocean/digitalocean
   types:
     - digitalocean_droplet
```
