### ISSUE TITLE
specifying project_path only in terraform_output module does not default to terraform.tfstate file, hence returns nothing

### ISSUE THREAD

**Issue by raedrizk** [ansible-collections/cloud.terraform#15]
##### SUMMARY
specifying project_path only in terraform_output module does not work. according to the documentation it should default to the state file with the name of terraform.tfstate in that directory, but the output shows 
"state_file": null

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
terraform_output

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.13 (main, Nov  9 2022, 13:16:24) [GCC 8.5.0 20210514 (Red Hat 8.5.0-15)] (/usr/bin/python3.9)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
1.0.0
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(env: ANSIBLE_FORCE_COLOR) = True
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_CALLBACK_PLUGIN_PATH(env: ANSIBLE_CALLBACK_PLUGINS) = ['/runner/artifacts/30/callback']
DEFAULT_LOAD_CALLBACK_PLUGINS(env: ANSIBLE_LOAD_CALLBACK_PLUGINS) = True
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = awx_display
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INVENTORY_UNPARSED_IS_FAILED(env: ANSIBLE_INVENTORY_UNPARSED_FAILED) = True
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False
```

##### OS / ENVIRONMENT

[ansibleadmin@ip-10-0-14-254 provision_aws_resources]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.6 (Ootpa)
[ansibleadmin@ip-10-0-14-254 provision_aws_resources]$ terraform --version
Terraform v1.3.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.44.0
[ansibleadmin@ip-10-0-14-254 provision_aws_resources]$ 

##### STEPS TO REPRODUCE

```yaml
  - name: Apply terraform plan
    cloud.terraform.terraform:
      force_init: true
      lock: true
      project_path: /var/terraform/plans/{{ working_dir_name }}
      variables_file: /var/terraform/plans/{{ working_dir_name }}/{{ tf_vars_file_name }}
      state: present
   

  - name: Read outputs from state file
    cloud.terraform.terraform_output:
      project_path: /var/terraform/plans/{{ working_dir_name }}
    register: terraform_state_file
```

##### EXPECTED RESULTS

The state file to be read and parsed

##### ACTUAL RESULTS

```paste below
JSON from terraform_output
{
  "outputs": {},
  "invocation": {
    "module_args": {
      "project_path": "/var/terraform/plans/provision_aws_resources",
      "format": "json",
      "name": null,
      "binary_path": null,
      "state_file": null
    }
  },
  "_ansible_no_log": null,
  "changed": false
}



```

**Comment by PolonaM** [comment]
@raedrizk "state_file": null under "invocation" means that you didn't specify state_file when calling the module terraform_output (and of course this is true since you specified project_path). The outputs from state file (in your example terraform.tfstate in project_path) should be seen under "outputs" - in your case this is an empty dict, so can you first check if you have any outputs defined in your .tf file in project_path?

**Comment by abikouo** [comment]
@raedrizk this is not an issue, the module is working as expected
As mentioned by @PolonaM, `state_file: null` under `invocation` means that you didn't specify state_file when calling the module terraform_output

I can successfully use the module with the following configuration

`main.tf`

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.16"
    }
  }
}

  required_version = ">= 1.2.0"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_vpc" "test-ansible" {
  cidr_block = var.vpc_cidr_block

  tags = {
    Name = "terraform-test"
  }
}

```

`output.tf`

```
output "vpc_arn" {
  description = "arn of the VPC instance"
  value       = aws_vpc.test-ansible.arn
}
```

Running the following playbook 

```
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Read terrafom output
      cloud.terraform.terraform_output:
        project_path: aws-provision
        format: json
```

Here is the output

```
PLAY [localhost] *********************************************************************************************************************************

TASK [Read terrafom output] **********************************************************************************************************************
ok: [localhost] => {"changed": false, "outputs": {"vpc_arn": {"sensitive": false, "type": "string", "value": "arn:aws:ec2:us-east-1:xxxxxxxxxxxx:vpc/vpc-0e21abf1c3865a918"}}}

PLAY RECAP ***************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

I am closing the issue as this is not reproducible.
