### ISSUE TITLE
Support Terraform Cloud with different workspaces

### ISSUE THREAD

**Issue by raspbeguy** [ansible-collections/cloud.terraform#150]
##### SUMMARY

As I understand there is two way to build an inventory using terraform states:

- `cloud.terraform.terraform_state` to query directly a state backend using provided backend configuration
- `cloud.terraform.terraform_provider` to query stated through local terraform project

I didn't manage to use `terraform_state`, with the following configuration:

```yaml
plugin: cloud.terraform.terraform_state
hostname: terraform.mydomain.example
backend_type: remote
backend_config:
  organization: my-org
  workspaces:
    name: my-workspace
```

For that reason I'm using Terraform Cloud with multiple workspaces. For now I'm successfully using `terraform_provider`.  My terraform configuration looks like this:

```hcl
terraform {
  cloud {
    hostname = "terraform.mydomain.examples"
    organization = "my-org"

    workspaces {
      tags = ["tag1", "tag2"]
    }
  }
  ...
}
```
I use `tags` instead of `workspace` parameter to enable using several workspaces.

The problem with `terraform_provider` is that I have to manually switch to the desired workspace by typing:

```
terraform workspace select myworkspace
```
I would rather have an option in `terraform_provider` to specify the workspace.

Another option would be to make `terraform_state` work with the remote option.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- `cloud.terraform.terraform_state`
- `cloud.terraform.terraform_provider`
