### ISSUE TITLE
Support setting workspaces in the inventory provider

### ISSUE THREAD

**Issue by diademiemi** [ansible-collections/cloud.terraform#160]
##### SUMMARY
The inventory provider does not support using workspaces to get the state, I would like to see this changed

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

[terraform_provider.py](https://github.com/ansible-collections/cloud.terraform/blob/main/plugins/inventory/terraform_provider.py)

##### ADDITIONAL INFORMATION
In the inventory provider you could place a `workspace` argument or the environment variable `TF_WORKSPACE`

```yaml
plugin: cloud.terraform.terraform_provider
project_path: "./terraform/infra/hetzner/"
state_file: ""
search_child_modules: true
workspace: "hetzner-terraform"
```

I currently have this working on my branch, if this would be accepted I can clean up the code, add tests and create a PR
