### ISSUE TITLE
Data source as extra variable for host

### ISSUE THREAD

**Issue by iMilkyWayR** [ansible-collections/cloud.terraform#169]
I'm trying to use the `cloud.terraform.terraform_state` inventory plugin. I have an LXC container in proxmox as a resource and an IP address as a data source, it looks like configuration below.
```yaml
resource "proxmox_lxc" "lxc" {
...
}

data "dns_a_record_set" "lxc_ip" {
...
}
```
terraform_state.yaml 
```yaml
plugin: cloud.terraform.terraform_state
backend_type: http
backend_config:
  address: "EDITED"
  username: "EDITED"
  password: "EDITED"
search_child_modules: true
hostnames:
  - hostname
provider_mapping:
  - provider_name: registry.terraform.io/telmate/proxmox
    types:
      - proxmox_lxc
```

With this configuration, I receive the correct inventory from the proxmox provider but is it possible to add an extra variable from the data source?

ANSIBLE VERSION
```
ansible [core 2.18.2]
  config file = /Users/imilkyway/.ansible.cfg
  configured module search path = ['/Users/imilkyway/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.2.0/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/imilkyway/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (/opt/homebrew/Cellar/ansible/11.2.0/libexec/bin/python)
  jinja version = 3.1.5
  libyaml = True
```

COLLECTION VERSION
```
Collection                               Version
---------------------------------------- ----------
cloud.terraform                          4.0.0-dev0
```
