### ISSUE TITLE
bug: Ansible booleans are not being mapped to Terraform booleans

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/cloud.terraform#24]
##### SUMMARY

Ansible booleans are not being mapped to Terraform booleans

https://github.com/ansible-collections/cloud.terraform/blob/main/plugins/modules/terraform.py#L375

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
[:~] $ ansible --version
ansible [core 2.11.12] 
  python version = 3.7.8 (default, Oct 25 2020, 11:34:54) [Clang 12.0.0 (clang-1200.0.32.21)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
1.0.0 from Ansible Galaxy
1.0.1 from GitHub Repo main branch
```

##### OS / ENVIRONMENT

```
macOS 13.1
```

##### STEPS TO REPRODUCE

```yaml
---
- name: "Ansible Playbook"
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Terraform init and Terraform apply - Module 1
    cloud.terraform.terraform:
      project_path: "{{ playbook_dir }}/tmp/terraform_module1"
      state: present
      force_init: true
      variables:
        variable_here: true
```

##### EXPECTED RESULTS

Parse Ansible bool type `true`, into Python bool type `True`, and then as the Terraform Input Variable bool type `true`.

Doc: https://developer.hashicorp.com/terraform/language/expressions/types#bool

##### ACTUAL RESULTS

Executed as Terraform Input Variable string with value `True`.

> _**N.B. It is almost always better to preserve Terraform Input Variable formatting, to create a *.tfvars and use operator `-var-file=`. For example, any input that is a SSH Key string will be mangled by `-var=X` and therefore instead use `terraform apply -var-file=default.tfvars` with key=value contained within.**_

```yaml
{
    "changed": false,
    "msg": "Terraform plan could not be created
STDOUT: 
STDERR: 
Error: Incorrect condition type

  on file.tf line 4, in data \"resource_class_here\" \"name_here\":
   4:   count = var.variable_here ? 0 : 1
    ├────────────────
    │ var.variable_here is \"True\"

The condition expression must be of type bool.

COMMAND: /usr/local/bin/terraform plan -lock=true -input=false -no-color
-detailed-exitcode -out /var/folders/a1/aa_aaaa/T/tmp11aa11.tfplan -var variable_here=True
}
```

##### WORKAROUND

Do not use Ansible Variable boolean, use string instead

```yaml
      variables:
        variable_here: 'true'
```

**Comment by anazobec** [comment]
Hi, to use ``variable_here: true`` instead of ``variable_here: 'true'``, you must use ``complex_vars: true`` before the ``variables`` block (shown below).
```yaml
---
- name: "Ansible Playbook"
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Terraform init and Terraform apply - Module 1
    cloud.terraform.terraform:
      project_path: "{{ playbook_dir }}/tmp/terraform_module1"
      state: present
      force_init: true
      complex_vars: true  # <-- this
      variables:
        variable_here: true
```
---------------------------------------------
**ANSIBLE VERSION**
```
ansible [core 2.14.1]
  python version = 3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = False
```
**OS / ENVIRONMENT**
```
Ubuntu 22.04.1 LTS
```
**STEPS TO REPRODUCE**
```yaml
---
- name: "Ansible Playbook"
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Terraform init and Terraform apply - Module 1
    cloud.terraform.terraform:
      project_path: "{{ playbook_dir }}/tmp/terraform_module1"
      state: present
      force_init: true
      complex_vars: true
      variables:
        variable_here: true
```
**EXPECTED RESULTS**
```shell
{
    "changed": false,
    "msg": "Terraform plan could not be created
STDOUT: 
STDERR: 
Error: Incorrect condition type

  on file.tf line 4, in data \"resource_class_here\" \"name_here\":
   4:   count = var.variable_here ? 0 : 1
    ├────────────────
    │ var.variable_here is \"True\"

The condition expression must be of type bool.

COMMAND: /usr/local/bin/terraform plan -lock=true -input=false -no-color
-detailed-exitcode -out /var/folders/a1/aa_aaaa/T/tmp11aa11.tfplan -var variable_here=True
}
```
**ACTUAL RESULTS**
```shell
PLAY [Ansible Playbook] **********************************************************************************************************************************************************************

TASK [Terraform init and Terraform apply - Module 1] *****************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```
