### ISSUE TITLE
feat request: Ansible Playbook constructs should equal Terraform Template constructs

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/cloud.terraform#26]
##### SUMMARY

At present, the Ansible Module `terraform` should be renamed as `terraform_template_run` which more appropriately describes the current capabilities. The Ansible Module within this Ansible Collection is a static execution of a pre-defined Terraform Template, it does not allow for any dynamic control by Ansible

feat request: Ansible Playbook constructs should equal Terraform Template constructs

        

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

By each Ansible Task acting as a construct for a Terraform Module, the Ansible Playbook achieves a level of parity with a Terraform Template. This allows Ansible to programatically/dynamically alter the desired infrastructure state being provisioned by Terraform.

By way of example, an Ansible Task might request `count` of a Terraform Module to provision equally _**OR**_ might loop to re-use the same Terraform Module but executed each time with different inputs.

It is not currently possible to treat each Ansible Task (within the Ansible Playbook) as if it were a Terraform Module Block call (within the Terraform Template).

See below as pseudocode example....

_**Terraform Template high-level design:**_
```hcl
# Terraform Providers declaration
terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws" # Obtain the Terraform Provider from the Terraform Registry
      version = "~> 4.0"
    }
  }
}

# Terraform Providers configuration
provider "aws" {
  region = "us-east-1"
  access_key = var.tf_template_input_var_aws_credential_key_access
  secret_key = var.tf_template_input_var_aws_credential_key_secret
}

module "run_aws_vpc_create" {
  source  = "terraform-aws-modules/vpc/aws" # Obtain the Terraform Module from the Terraform Registry
#  source = "github.com/terraform-aws-modules/terraform-aws-vpc?ref=main" # From GitHub repository
  terraform_module_variable1  =   "static"
}

module "run_aws_ec2_instance_create" {
  source  = "terraform-aws-modules/ec2-instance/aws" # Obtain the Terraform Module from the Terraform Registry
  terraform_module_variable2  =   module.run_aws_vpc_create.expected_output_from_module1
}

variable "tf_template_input_var_aws_credential_key_access" {
  description = "Text"
}

variable "tf_template_input_var_aws_credential_key_secret" {
  description = "Text"
}
```

_**Ansible Playbook for executing Terraform Modules high-level proposed design:**_
```yaml
---
- name: "Ansible Playbook to provision infrastructure using Terraform"
  hosts: local
  gather_facts: false

  vars_prompt:
    - name: terraform_template_input1
      prompt: Please enter value
      private: no
    - name: aws_credential_key_access
      prompt: Please enter value
      private: no
    - name: aws_credential_key_secret
      prompt: Please enter value
      private: no

  tasks:

  - name: Terraform Template build - Terraform version and Terraform Providers
    cloud.terraform.terraform_template_build:
      project_path: "{{ playbook_dir }}/tf_template"
      terraform_version: ">= 1.0"
      provider_upgrade: true # terraform init will use `-upgrade` flag
      providers:
        - name: hashicorp/aws
          version: "~> 4.0"
          arguments:
            - region: "us-east-1"
            - access_key = "var.tf_template_input_var_aws_credential_key_access"
            - secret_key = "var.tf_template_input_var_aws_credential_key_secret"
      modules:
        - title: "run_aws_vpc_create"
          source: "terraform-aws-modules/vpc/aws" # Obtain the Terraform Module from the Terraform Registry
          arguments:
            - terraform_module_variable1: "{{ terraform_template_input1 }}"
        - title: "run_aws_ec2_instance_create"
          source: "terraform-aws-modules/ec2-instance/aws" # Obtain the Terraform Module from the Terraform Registry
          arguments:
            - terraform_module_variable2: "module.run_aws_vpc_create.expected_output_from_module1"
      input_variables:
        - name: tf_template_input_var_aws_credential_key_access
          desc: "Text"
        - name: tf_template_input_var_aws_credential_key_secret
          desc: "Text"
      state: present

  - name: Terraform init and Terraform apply - Module 1
    cloud.terraform.terraform_template_run:
      project_path: "{{ playbook_dir }}/tf_template"
      state: present
      input_variables:
        tf_template_input_var_aws_credential_key_access: "{{ aws_credential_key_access }}"
        tf_template_input_var_aws_credential_key_secret: "{{ aws_credential_key_secret }}"
```

**Comment by sean-freeman** [comment]
#### Workaround, download Terraform Modules from GitHub, add Terraform Provider declaration file and execute

This requires downloading the Terraform Module from GitHub source code instead of the versions released via the Terraform Registry; no difference in the code but not following Terraform best practices.

Thereafter each Terraform Module is executed per Ansible Task, and JSON output from Ansible Task for Terraform Module 1 will be passed using Ansible to the Ansible Task for Terraform Module 2. This means individual Terraform state files, and Terraform will be unaware of the relationship between each Terraform Module and unable to resolve dependencies in the future.

**NOTE:** Use static region definition, workaround does not work with variable insertion into AWS Availability Zones due to Ansible Module for Terraform performing incorrect parsing, see Issue #27 .....
`azs: '["{{ ansible_var_aws_region }}a", "{{ ansible_var_aws_region }}b", "{{ ansible_var_aws_region }}c"]'`
results in
`-var 'azs=['\"'\"'us-west-2a'\"'\"', '\"'\"'us-west-2b'\"'\"', '\"'\"'us-west-2c'\"'\"']'`
instead of
`-var 'azs=[\"us-west-2a\", \"us-west-2b\", \"us-west-2c\"]'`

Workaround code:
```yaml
---

- name: "Ansible Playbook"
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: ansible_var_aws_access_key
      prompt: Please enter AWS Access Key
      private: no
    - name: ansible_var_aws_secret_access_key
      prompt: Please enter AWS Secret Access Key
      private: yes
    - name: ansible_var_aws_region
      prompt: Please enter AWS Region
      private: no
    - name: ansible_var_aws_resources_prefix
      prompt: Please enter prefix for AWS resources
      private: no

  tasks:

  - name: Terraform Module for AWS VPC - Git clone
    ansible.builtin.git:
      repo: 'https://github.com/terraform-aws-modules/terraform-aws-vpc.git'
      dest: "{{ playbook_dir }}/tmp/terraform-aws-vpc"
      version: master

  # Providers within Terraform Modules - https://developer.hashicorp.com/terraform/language/modules/develop/providers
  - name: Terraform Module for AWS VPC - Create Terraform providers information inside of each Terraform Module
    ansible.builtin.copy:
      dest: "{{ playbook_dir }}/tmp/terraform-aws-vpc/tf_provider.tf"
      content: |
        # Terraform Provider declaration
        provider "aws" {
        }

  - name: Terraform Module for AWS VPC - Terraform init and Terraform apply
    register: terraform_result
    environment:
      AWS_ACCESS_KEY_ID: "{{ ansible_var_aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ ansible_var_aws_secret_access_key }}"
      AWS_REGION: "{{ ansible_var_aws_region }}"
    cloud.terraform.terraform:
      project_path: "{{ playbook_dir }}/tmp/terraform-aws-vpc"
      state: present
      force_init: true
      variables:
        name: "{{ ansible_var_aws_resources_prefix }}"
        cidr: "10.0.0.0/16"
        azs: '["us-west-2a", "us-west-2b", "us-west-2c"]'
        private_subnets: '["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]'
        public_subnets: '["10.0.11.0/24", "10.0.12.0/24", "10.0.13.0/24"]'
        database_subnets: '["10.0.21.0/24", "10.0.22.0/24", "10.0.23.0/24"]'
        elasticache_subnets: '["10.0.31.0/24", "10.0.32.0/24", "10.0.33.0/24"]'
        redshift_subnets: '["10.0.41.0/24", "10.0.42.0/24", "10.0.43.0/24"]'
        intra_subnets: '["10.0.51.0/24", "10.0.52.0/24", "10.0.53.0/24"]'
        private_subnet_names: '["Private Subnet One", "Private Subnet Two"]'
        database_subnet_names: '["DB Subnet One"]'
        elasticache_subnet_names: '["Elasticache Subnet One", "Elasticache Subnet Two"]'
        redshift_subnet_names: '["Redshift Subnet One", "Redshift Subnet Two", "Redshift Subnet Three"]'
        intra_subnet_names: []
        create_database_subnet_group: 'false'
        manage_default_network_acl: 'true'
        default_network_acl_tags: '{ Name = "{{ ansible_var_aws_resources_prefix }}-default" }'
        manage_default_route_table: 'true'
        default_route_table_tags: '{ Name = "{{ ansible_var_aws_resources_prefix }}-default" }'
        manage_default_security_group: 'true'
        default_security_group_tags: '{ Name = "{{ ansible_var_aws_resources_prefix }}-default" }'
        enable_dns_hostnames: 'true'
        enable_dns_support: 'true'
        enable_nat_gateway: 'true'
        single_nat_gateway: 'true'
        customer_gateways: | 
          {
            IP1 = {
              bgp_asn     = 65112
              ip_address  = "1.2.3.4"
              device_name = "some_name"
            },
            IP2 = {
              bgp_asn    = 65112
              ip_address = "5.6.7.8"
            }
          }
        enable_vpn_gateway: 'true'
        enable_dhcp_options: 'true'
        dhcp_options_domain_name: "service.consul"
        dhcp_options_domain_name_servers: '["127.0.0.1", "10.10.0.2"]'
        enable_flow_log: 'true'
        create_flow_log_cloudwatch_log_group: 'true'
        create_flow_log_cloudwatch_iam_role: 'true'
        flow_log_max_aggregation_interval: 60
```
