### ISSUE TITLE
inventory_from_outputs Ansible Role does not permit static values

### ISSUE THREAD

**Issue by sean-freeman** [ansible-collections/cloud.terraform#41]
##### SUMMARY
inventory_from_outputs Ansible Role does not permit static values

The Ansible Role assumes always that Terraform should be aware of the OS Login User and the target Ansible Inventory Group.

In addition, mapping variable `"name"` is very generic. It would be clearer to prefix every value with `host_`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`cloud.terraform.inventory_from_outputs`

##### COLLECTION VERSION
`1.0.x`

##### CONFIGURATION example
```yaml
- hosts: localhost
  roles:
    - role: cloud.terraform.inventory_from_outputs
      project_path: "{{ playbook_dir }}/terraform_template"
      mapping_variables:
        host_lists: terraform_var_host_list
        name: terraform_var_name
        ip: terraform_var_ip
        user: "root"
        group: "ansible_inv_group1"
```

##### ACTUAL RESULTS

Cannot replicate, this bug represents a design decision that should be investigated and alterations accordingly
