### ISSUE TITLE
Command field in result has spaces between characters

### ISSUE THREAD

**Issue by gravesm** [ansible-collections/cloud.terraform#75]
##### SUMMARY

The command that is returned in the result when the module succeeds has `" ".join(command)` called twice, resulting in a space between each character of the returned value. For example:

```
changed: [localhost] => {
    "changed": true,
    "command": "a p p l y   - n o - c o l o r   - i n p u t = f a l s e   - a u t o - a p p r o v e   - l o c k = t r u e   / t m p / t m p 7 u r j _ 0 2 _ . t f p l a n",
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

terraform

##### STEPS TO REPRODUCE

playbook:
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - cloud.terraform.terraform:
        project_path: ./
        force_init: true
```
tf config:
```
resource "local_file" "test" {
  content  = "asdf"
  filename = "/tmp/testfile"
}
```
