### ISSUE TITLE
Support for workspaces in lookups

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-collections/cloud.terraform#85]
##### SUMMARY
I'd like to use a different workspace when using the lookup-plugin.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
tf_output_lookup

##### ADDITIONAL INFORMATION

Example code:

```yaml
- name: get all outputs from custom state file
  ansible.builtin.debug:
    msg: "{{ lookup('cloud.terraform.tf_output', workspace='dev', state_file='path/to/custom/state/file') }}"
```
